Durack Mar24 updates (#542)
PCMDI/pcmdi.github.io pull request #543
Opened 2024-03-03 19:40 UTC by durack1

Fix #542

2024-03-03 19:41 UTC, durack1 commented
@mauzey1 please review when you get a moment, no rush on this

2024-03-04 18:02 UTC, mauzey1 requested changes

2024-03-04 18:13 UTC, durack1 commented
@mauzey1 thanks for checking, that fix should now be in place

2024-03-04 18:17 UTC, mauzey1 approved these changes

2024-03-04 18:17 UTC, merged